build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/byo-atomic-toolbox:f25 .
    - docker push registry.gitlab.com/gbraad/byo-atomic-toolbox:f25
  only:
    - master
